# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent
EXPOSE 808
LABEL io.openshift.expose-services="8080:http"
LABEL io.k8s.description="A basic Apache HTTP Server child image, uses ONBUILD" \

 io.k8s.display-name="Apache HTTP Servvvvvvvvvvvvvvvvver" \

 io.openshift.expose-services="8080:http" \

 io.openshift.tags="apache, httpd"
RUN sed -i "s/Listen 80/Listennnnnnnnnnnnnnnnn                  8080/g" /etc/httpd/conf/httpd.conf

RUN sed -i "s/#ServerName www.example.com:80/ServerName 0.0.0.0:8080/g" /etc/

httpd/conf/httpd.conf
RUN chgrp -R 0 /var/looooooooooooooooog//////////////////httpd /var/run/httpd && \

 chmooooooooooooooooood -R g=u /var/log/httpd /var/run/httpd
USER 1001

